version: '3.9'

services:
  request_api:
    container_name: request_api
    image: request-api:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL = ${DB_URL}
      - DB_USER = ${DB_USER}
      - DB_PASSWORD = ${DB_PASSWORD}
    depends_on:
      - request_db
  request_db:
    container_name: request_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB = ${DB_NAME}
      - POSTGRES_USER = ${DB_USER}
      - POSTGRES_PASSWORD = ${DB_PASSWORD}